[박대현] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/26-westagram-backend pull request #43
Opened 2021-10-25 07:56 UTC by 1119pdh

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 기능 추가
		 
## 수정 사항들 자세한 내용
- views.py에 UserlistView 생성 
- users 앱에 urls.py 생성후 알맞은 경로 설정, 프로젝트 westargram도 urls.py 알맞게 수정 
- 이메일에 문자열이 없거나, @ 또는 . 이없거나 고유하지 않으면 알맞은 메세지와 400에러 반환 
- 패스워드에 특수문자, 문자, 숫자가 포함되지 않으면 메세지와 400에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-25 08:40 UTC, lordmyshepherd requested changes

2021-10-25 08:40 UTC, lordmyshepherd commented on students/parkdaehyun/users/urls.py
> +
빈 줄 한칸 지워주세요~

2021-10-25 08:40 UTC, lordmyshepherd commented on students/parkdaehyun/users/views.py
> +            return JsonResponse({"message" : "동일한 이메일이 존재합니다."}, status=400)
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

if not re.match(REGEX_EMAIL, value):
    ....

if not re.match(REGEX_EMAIL, value):
    .....
```

2021-10-25 08:40 UTC, lordmyshepherd commented on students/parkdaehyun/users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status = 201)
else문은 불필요할 것 같네요~ 사용해도 상관 없지만, 한 줄이라도 더 줄여보죠~
추가로 line 37과 38 사이는 한 칸 띄워주세요~

```suggestion
            User.objects.create(
                name                 = data["name"],
                email                = data["email"],
                password             = data["password"],
                telephone            = data["telephone"],
                personal_information = data["personal_information"],
            )
            
            return JsonResponse({"message" : "SUCCESS"}, status = 201)
```

2021-10-25 08:52 UTC, 1119pdh commented on students/parkdaehyun/users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status = 201)
바꿧습니다~~ 리뷰 감사합니다.

2021-10-25 10:13 UTC, lordmyshepherd requested changes

2021-10-25 10:13 UTC, lordmyshepherd commented on students/parkdaehyun/users/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status=400)
Dictionary에 접근하는 경우는 두 가지 방법이 있습니다. 

첫번째 방법은 `data["email"]`로 접근하는 방법입니다. 이 경우에 matching되는 key값이 없는 경우에는 파이썬이 error를 raise합니다. 그렇기 때문에 except KeyError로 빠지게 되고 아래와 같은 if문 코드는 필요가 없게 됩니다.

```python
if not (password and email):
    return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
```

두번째 방법은 `data.get("email")`로 접근하는 방법입니다. 이 경우는 matching되는 key 값이 없는 경우에 None을 반환하기 때문에 아래와 같이 if문으로 에러를 처리할 수 있습니다.

```python
if not (password and email):
    return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
```

2021-10-25 11:04 UTC, 1119pdh commented on students/parkdaehyun/users/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status=400)
바꿨습니다. 친절한 설명 감사합니다~~

2021-10-26 01:45 UTC, ghost requested changes

2021-10-26 01:45 UTC, ghost commented on students/parkdaehyun/users/urls.py
> +
대현님 빈 줄 한 칸 지워주세요!

2021-10-26 02:31 UTC, 1119pdh commented
빈줄한칸지웠습니다~

2021-10-26 05:33 UTC, ghost requested changes
대현님 수정 마지막!! 확인해주세요!!

2021-10-26 05:33 UTC, ghost commented on students/parkdaehyun/users/views.py
> +        personal_information = data["personal_information"],
align 맞춰주세요! 컨벤션 관련 리뷰도 반드시 잘 반영되어 있는 지 확인하고 PR 올려주세요

```
            User.objects.create(
                name                 = data["name"],
                email                = data["email"],
                password             = data["password"],
                telephone            = data["telephone"],
                personal_information = data["personal_information"],
            )
            
            return JsonResponse({"message" : "SUCCESS"}, status = 201)

```

2021-10-26 05:45 UTC, 1119pdh commented on students/parkdaehyun/users/views.py
> +        personal_information = data["personal_information"],
바꿨습니다~~ PR 올릴 때 하나하나 다시 체크!

2021-10-26 05:50 UTC, ghost approved these changes
LGTM 🥳

2021-10-26 05:50 UTC, merged