[유병문] Mission 2 : 모델링
wecode-bootcamp-korea/26-westagram-backend pull request #47
Opened 2021-10-25 08:43 UTC by qudans1237

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-25 10:10 UTC, lordmyshepherd requested changes

2021-10-25 10:10 UTC, lordmyshepherd commented on students/byungmoon/westargram/users/models.py
> +    email = models.CharField(max_length=200)
email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2021-10-25 10:10 UTC, lordmyshepherd commented on students/byungmoon/westargram/users/models.py
> +    password = models.CharField(max_length=100)
password는 이후에 암호화해서 저장해야하기 때문에 max_length=200으로 수정해주세요.

2021-10-25 10:10 UTC, lordmyshepherd commented on students/byungmoon/westargram/users/models.py
> +    OtherPersonalInf = models.CharField(max_length=200)
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-10-25 10:10 UTC, lordmyshepherd commented on students/byungmoon/westargram/users/models.py
> +    OtherPersonalInf = models.CharField(max_length=200)
스네이크 케이스로 만들어주세요~
```suggestion
    other_personal_info = models.CharField(max_length=200)
```

2021-10-26 01:51 UTC, ghost requested changes

2021-10-26 01:51 UTC, ghost commented on students/byungmoon/westargram/users/models.py
> +    Other_Personal_Inf = models.CharField(max_length=200)
변수명은 소문자로 사용합니다~!
```
other_personal_inf = models.CharField(max_length=200)
```

2021-10-26 05:49 UTC, ghost requested changes
병문님 `feature/suntae-models` 브랜치에는 `user` model과 관련된 내용만 있어야 합니다.
`sign-up` 관련 로직은 다른 브랜치 생성해서 작성해주세요. 해당 브랜치에서는 제외 시켜주세요

2021-10-26 05:49 UTC, ghost commented
`model.py` 내용만 남겨주고 삭제해주세요.

2021-10-26 06:59 UTC, ghost approved these changes
LGTM 🥳

2021-10-26 07:00 UTC, merged