[권상현] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/26-westagram-backend pull request #50
Opened 2021-10-25 09:07 UTC by gshduet

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이름, 비밀번호, 생일, 이메일주소, 핸드폰번호를 필수적으로 받으며 sns주소는 선택적으로 추가 가능
- 회원가입 시간 기록

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-25 10:28 UTC, lordmyshepherd requested changes

2021-10-25 10:28 UTC, lordmyshepherd commented on students/sanghyun/users/views.py
> +                return JsonResponse({"message": "EMAIL_EXISTS"}, status=409)
한 줄씩 띄워주세요~
```suggestion
            if not re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
                
            if not re.match('^(?=.*[A-Za-z])(?=.*\d)(?=.*[?!@#$%*&])[A-Za-z\d?!@#$%*&]{8,}$', password):
                return JsonResponse({"message": "INVALID_PASSWORD"}, status=400)
                
            if User.objects.filter(email=email).exists():
                return JsonResponse({"message": "EMAIL_EXISTS"}, status=409)
```

2021-10-25 10:28 UTC, lordmyshepherd commented on students/sanghyun/users/views.py
> +            return JsonResponse({"MESSAGE" : "KEY_ERROR"}, status = 400)
`except`만 사용하게 되면 모든 에러 케이스의 경우에 except 로직을 타게됩니다.
이렇게 되면 어떤 에러가 발생했는지 명확하게 알 수 없기 때문에 `디버깅`하기가 어렵습니다.

디버깅하기 쉽게 만들어야 합니다.
`KeyError`를 명확하게 잡아주세요!

2021-10-25 10:40 UTC, gshduet commented on students/sanghyun/users/views.py
> +                return JsonResponse({"message": "EMAIL_EXISTS"}, status=409)
space 추가 완료했습니다!

2021-10-25 10:40 UTC, gshduet commented on students/sanghyun/users/views.py
> +            return JsonResponse({"MESSAGE" : "KEY_ERROR"}, status = 400)
except : 에서

except KeyError: 로 수정 완료 했습니다!

2021-10-26 01:52 UTC, ghost approved these changes
LGTM🥳

2021-10-26 01:53 UTC, merged