[장재원] Mission 6: 로그인 JWT 적용
wecode-bootcamp-korea/26-westagram-backend pull request #51
Opened 2021-10-25 09:53 UTC by Jang-Jaewon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- pyjwt를 사용하여 로그인 성공 시, token 발행 로직 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 요청된 email이 DB에 존재하지 않으면, except 구문으로 에러 처리
- 해당 email이 존재한다면 DB상의 password와 전달받은 password를 bcrypt를 통해 일치여부 검증
- 비밀번호까지 인증되었다면 pyjwt를 통해 token 발행하여 response로 전달

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 데코레이션은 좀 더 공부해서 일번주 내에 꼭 도전하겠습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-25 10:31 UTC, lordmyshepherd requested changes

2021-10-25 10:31 UTC, lordmyshepherd commented on students/jaewon/users/views.py
>              return JsonResponse({"message": "KEY_ERROR"}, status=400)
KeyError와 Account.DoesNotExist error는 별도로 잡아주셔야 합니다.
`Account.DoesNotExist`는 KeyErro가 아니라 database 관련 error입니다!

2021-10-25 10:31 UTC, lordmyshepherd commented on students/jaewon/users/views.py
> +            user = Account.objects.get(email=email)
line 52 53 한 칸 띄워주세요!
```suggestion
            user = Account.objects.get(email=email)
            
```

2021-10-25 10:31 UTC, lordmyshepherd commented on students/jaewon/users/views.py
>                  return JsonResponse({"message": "INVALID_USER"}, status=401)
한 줄로 수정해도 될 것 같습니다!
```suggestion
            if bcrypt.checkpw(password.encode("utf-8"), user.password.encode("utf-8")):
                access_token = jwt.encode({"user_id": user.id}, SECRET_KEY, algorithm=ALGORITHM)
                
                return JsonResponse({"access_token": access_token}, status=200)

            return JsonResponse({"message": "INVALID_USER"}, status=401)
```

2021-10-25 11:02 UTC, Jang-Jaewon commented on students/jaewon/users/views.py
>              return JsonResponse({"message": "KEY_ERROR"}, status=400)
get 방식으로 DB에서 해당 사용자에 대한 객체를 찾아올 때, 없는 아이디로 HTTP 요청 시도하면 DoesNotExist 발생되서 filter로 처리할까하다가 에러를 처리하였습니다. 아래 분리하여 except 구문 만들었습니다. 혹시 filter가 더 적절하다면 다시 수정하겠습니다.

2021-10-25 11:02 UTC, Jang-Jaewon commented on students/jaewon/users/views.py
> +            user = Account.objects.get(email=email)
수정하였습니다.

2021-10-25 11:02 UTC, Jang-Jaewon commented on students/jaewon/users/views.py
>                  return JsonResponse({"message": "INVALID_USER"}, status=401)
계속 자동 줄바꿈되서 해결방법을 찾아보다 pyproject.tomi 파일 생성해서 max line값 주고, 해당 파일을 .gitignore에 추가하였습니다!

2021-10-26 01:58 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-10-26 01:59 UTC, merged