[유병문] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/26-westagram-backend pull request #71
Opened 2021-10-26 08:42 UTC by qudans1237

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-26 08:57 UTC, bigfanoftim requested changes

2021-10-26 08:57 UTC, bigfanoftim commented on students/byungmoon/westargram/users/urls.py
> +    path('/signin', SignInView.as_view()),
들여쓰기 맞춰주세요!
```suggestion
	path('/signup', SignUpView.as_view()),
      path('/signin', SignInView.as_view()),
```

2021-10-26 08:57 UTC, bigfanoftim commented on students/byungmoon/westargram/users/views.py
> +            password = [data'password']
틀린 문법이라 테스트가 제대로 되지 않았을 것 같아요! 문법 수정해주세요~
PR 올리시기 전에 체크, 올리신 후에도 한번 더 확인 부탁드립니다!
```suggestion
            password = data['password']
```

2021-10-26 08:57 UTC, bigfanoftim commented on students/byungmoon/westargram/users/urls.py
> +from users.views import SignUpView, SignInView
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

이 부분도 올리시기 전, 후에 한번 더 확인 부탁드립니다!

```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2021-10-26 09:03 UTC, qudans1237 commented on students/byungmoon/westargram/users/urls.py
> +    path('/signin', SignInView.as_view()),
넵! 확인했습니다

2021-10-26 09:03 UTC, qudans1237 commented on students/byungmoon/westargram/users/views.py
> +            password = [data'password']
넵! 확인했습니다

2021-10-26 09:04 UTC, qudans1237 commented on students/byungmoon/westargram/users/urls.py
> +from users.views import SignUpView, SignInView
넵! 확인했습니다

2021-10-26 09:06 UTC, ghost requested changes

2021-10-26 09:06 UTC, ghost commented on students/byungmoon/westargram/users/urls.py
> +    path('/signin', SignInView.as_view()),
줄 간격 맞춰주세요!

2021-10-26 09:08 UTC, qudans1237 commented on students/byungmoon/westargram/users/urls.py
> +    path('/signin', SignInView.as_view()),
넵! 확인했습니다

2021-10-27 01:27 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-10-27 01:27 UTC, merged