[권상현] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/26-westagram-backend pull request #75
Opened 2021-10-26 11:34 UTC by gshduet

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 시 입력한 비밀번호 bcrypt를 활용해 암호화 완료
- 회원가입 post 전송 후 암호화 완료 확인 완료
- 
<img width="1424" alt="스크린샷 2021-10-26 오후 8 13 52" src="https://user-images.githubusercontent.com/39396492/138866960-ff54b640-d9ce-4bde-aedf-6d4e94544f25.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- bcrypt 라이브러리를 활용해 해싱하는 과정에서 비밀번호로 입력한 str 자료형을 인코딩 후 소금을 칠한 뒤 다시 디코딩하는 과정은 이해 됐습니다. 이 과정을 한 줄로 구현하는 것과 해싱과 디코딩을 따로 때어 구현하는 것이 크게 차이가 있는지, 실무에선 어느 쪽을 선호하는지 궁금합니다. 
- 
- 공식문서에서도, 예시 영상에서도, 다른 동기님들도 UTF-8을 이용해 인코딩을 하기에 저 역시 UTF-8 방식으로 인코딩을 했습니다.
- 후에 UTF-8이 사용하는 용량과 ASCII가 사용하는 용량이 다르니 원시적이지만 더 가벼운 ASCII 도 쓸 수 있지 않을까 하는 개인적인 궁금증으로 인코딩 방식을 UTF-8에서 ASCII로 바꾼 뒤 post를 보냈을 때도 큰 문제 없이 아이디가 생성 됐습니다. 
- 물론 유니코드가 국제표준 문자표이고 UTF-8이 다른 UTF에 비해서 효율적인 인코딩 방식이기에 UTF-8 사용하는 것은 이해가 가지만, // 대부분의 사이트에서 회원가입 시 비밀번호를 입력할 때 한정된 특수기호와 영어, 숫자만 요구하니 굳이 UTF-8을 쓸 필요 없이 더 원시적인 ASCII를 써도 되는 것이 아닌지가 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-27 01:38 UTC, lordmyshepherd requested changes

2021-10-27 01:38 UTC, lordmyshepherd commented on students/sanghyun/requirements.txt
> +urllib3==1.26.7
`pip install django`와 같이 파이썬 패키지를 설치하게되면 관련 패키지에 필요한 다른 패키지도 같이 설치됩니다. 그렇기 때문에 단순히 `pip freeze > requirements.txt` 명령어를 사용해서 requirements.txt 파일을 생성할 경우에 정확히 어떤 패키지를 설치했는지 알 수 없습니다. 그렇기 때문에 아래와 같이 설치한 패키지와 버전만을 requirements.txt 파일에 추가해주셔야 합니다.

```bash
# requirements.txt

Django==3.1.2
django-cors-headers==3.10.0
mysqlclient==2.0.3
```

2021-10-27 03:22 UTC, gshduet commented on students/sanghyun/requirements.txt
> +urllib3==1.26.7
어떤 패키지를 설치했는지 확인하는 과정에서 저도 모르게 업데이트 된 것 같습니다. 바로 수정하도록 하겠습니다.

2021-10-27 08:33 UTC, ghost requested changes

2021-10-27 08:33 UTC, ghost commented on students/sanghyun/users/views.py
> +                password    = (bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())).decode('utf-8'),
create() 메서드 사용 전에 변수 선언으로 hashed 시킨 후 저장하는 로직으로 바꿔주세요!
```
hashed_password= bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")

User.objects.create(
     name = name,
     password = hashed_password)
```

2021-10-27 11:28 UTC, gshduet commented on students/sanghyun/users/views.py
> +                password    = (bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())).decode('utf-8'),
create() 메서드 내에서 해시 된 비밀번호 저장하는 로직에서
메서드 외부에서 비밀번호 해시 후 메서드 내에 적용하는 로직으로
변경 완료했습니다.

2021-10-28 01:22 UTC, ghost requested changes

2021-10-28 01:22 UTC, ghost commented on students/sanghyun/users/views.py
> +import json, re, bcrypt
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(python convention 문서 참고해주세요.)

```bash
```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```
```

2021-10-28 03:32 UTC, gshduet commented on students/sanghyun/users/views.py
> +import json, re, bcrypt
모듈 import 순서 정비 완료했습니다!

2021-10-28 04:56 UTC, ghost approved these changes
LGTM🥳

2021-10-28 04:56 UTC, merged