[김봉철] Mission 6: 로그인 JWT 적용
wecode-bootcamp-korea/26-westagram-backend pull request #76
Opened 2021-10-26 12:13 UTC by solarrrrr1010

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- jwt 토큰 발행
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인에 성공하면 토큰값 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-27 01:54 UTC, lordmyshepherd requested changes

2021-10-27 01:54 UTC, lordmyshepherd commented on students/bong/users/views.py
> +        return JsonResponse({"message" : "INVALID_USER"}, status=401)
1. 에러 처리를 할 때에는 if문 보다는 try, except를 사용하는 것이 가독성 측면에서 좋을 수 있습니다.
   if문을 `try + except User.DoesNotExist:` 문으로 바꿀 수 있습니다. 공식문서에서 한번 찾아보세요~
2. 'HS256' 알고리즘은 my_settings.py에 환경변수로 등록해서 관리해주세요! 
3. my_settings.py에서 환경변수를 import해서 사용하실 때에는 지금처럼 `from my_settings import ALGORITHM, SECRET_KEY` 방법이 아니라 `from django.conf.settings import  ALGORITHM, SECRET_KEY`를 사용해서 환경변수를 불러와서 사용해주세요. (django에서 추천하는 방법)

```suggestion
        try:
            user = User.objects.get(email=email)
            
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                token = jwt.encode({"id" : user.id}, SECRET_KEY, algorithm=ALGORITHM)
                
                return JsonResponse({"TOKEN" : token}, status=200)
                
         except User.DoesNotExist:
            return JsonResponse({"message" : "USER_DOES_NOT_EXISTS"}, status=401)            
```

2021-10-28 07:49 UTC, ghost requested changes

2021-10-28 07:49 UTC, ghost commented on students/bong/users/views.py
> +        print(data)
디버깅을 위한 `print()` 삭제해주세요

2021-10-28 07:49 UTC, ghost commented on students/bong/users/views.py
> +        return JsonResponse({"message" : "SUCCESS"}, status=200)
created 성공했을 때 반환하는 적절한 status code는 201 입니다. 
MDN에서 `http status code` 자료 추가로 확인 해보세요!

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2021-10-28 07:49 UTC, ghost commented on students/bong/users/views.py
> +
불필요한 공백 삭제해주세요

2021-10-28 07:49 UTC, ghost commented on students/bong/users/views.py
> +            return JsonResponse({"message" : "USER_DOES_EXISTS"}, status=401)
`keyerror` 에 대한 처리도 해주세요!

2021-10-28 07:49 UTC, ghost commented on students/bong/users/views.py
> +                return JsonResponse({"TOKEN" : token}, status=200)
`if` 로 처리 잘 하셨습니다. `if not` 으로 처리할 때 효율적으로 메모리 사용할 수 있으므로 아래와 같이 처리하는 방법도 있습니다.
성공했을 경우 토큰과 함께 성공 메세지도 함께 전달해주세요.

```
            if not bcrypt.checkpw(data["password"].encode("utf-8"), hashed_password):
                return JsonResponse({"MESSAGE":"INVALID_USER"}, status=401)

            access_token = jwt.encode({"id" : user.id}, SECRET_KEY, algorithm = ALGORITHM)

            return JsonResponse({"MESSAGE":"SUCCESS", "ACCESS_TOKEN": access_token}, status=200)
        
```

2021-10-28 08:40 UTC, solarrrrr1010 commented on students/bong/users/views.py
> +                return JsonResponse({"TOKEN" : token}, status=200)
회원가입 함수 내에서 선언된 hashed_password과 로그인시에도 사용이 가능한가요?

2021-10-28 12:21 UTC, ghost approved these changes
LGTM 🥳

2021-10-28 12:21 UTC, merged