[권상현] Mission 6: 로그인 JWT 적용
wecode-bootcamp-korea/26-westagram-backend pull request #87
Opened 2021-10-28 06:00 UTC by gshduet

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 JWT 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 비밀번호 검증 후 일치 시 JWT 토큰 생성
<img width="1085" alt="스크린샷 2021-10-28 오후 2 50 49" src="https://user-images.githubusercontent.com/39396492/139195975-f9bb1284-36e5-4976-870b-f61ea401c119.png">
- 이메일 혹은 비밀번호가 맞지 않을 시 'CHECK_YOUR_ID/PASSWORD' 문구 출력
<img width="1085" alt="스크린샷 2021-10-28 오후 2 51 16" src="https://user-images.githubusercontent.com/39396492/139195993-a053110d-8218-4452-b391-ec42191c5add.png">
- 데이터베이스에 이메일이 존재하지 않을 시 'USER_DOESN'T_EXISTS' 문구 출력
<img width="1085" alt="스크린샷 2021-10-28 오후 2 51 45" src="https://user-images.githubusercontent.com/39396492/139196036-ead0aee6-a484-40d9-8e48-93573c9a7084.png">
- 이메일 혹은 패스워드 둘 중 하나 누락 후 입력 시 'KEY_ERROR' 문구 출력
<img width="1085" alt="스크린샷 2021-10-28 오후 2 51 24" src="https://user-images.githubusercontent.com/39396492/139196102-6f0cd119-f8d4-43f5-88b0-f8c4970dc96a.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-10-28 06:52 UTC, bigfanoftim requested changes

2021-10-28 06:52 UTC, bigfanoftim commented on students/sanghyun/users/views.py
> +            return JsonResponse({"MESSAGE": "CHECK_YOUR_ID/PASSWORD"}, status = 401)
if not 활용해서 아래와 같이 하실 수도 있습니다!

```suggestion
            if not bcrypt.checkpw(password.encode("utf-8"), user_info.password.encode("utf-8")):
                return JsonResponse({"MESSAGE": "CHECK_YOUR_PASSWORD"}, status = 400)
                
            token = jwt.encode({'id': user_info.id}, SECRET_KEY, algorithm = ALGORITHM)
            return JsonResponse({'MESSAGE' : 'LOGIN_SUCCESS', 'TOKEN' : token}, status = 200)

            
```

2021-10-28 07:37 UTC, gshduet commented on students/sanghyun/users/views.py
> +            return JsonResponse({"MESSAGE": "CHECK_YOUR_ID/PASSWORD"}, status = 401)
다음번엔 try와 if, if not의 차이를 고려해서 코드 작성해 보도록 하겠습니다! 감사합니다~

2021-10-28 08:34 UTC, ghost requested changes
상현님 수고하셨습니다! 아래 리뷰 확인해주세요

2021-10-28 08:34 UTC, ghost commented on students/sanghyun/users/views.py
> +                return JsonResponse({"MESSAGE": "CHECK_YOUR_EMAIL/PASSWORD"}, status = 400)
JsonResponse는 프론트 개발자가 받기 때문에 너무 상세하게 쓸 필요는 없습니다.
`{'MESSAGE' : 'INVAILD USER'}' 정도로 작성해도 됩니다.

HTTP 통신 시 텍스트로 서버와 클라이언트가 주고 받기 때문에 내용을 탈취하여 제 3자가 볼 수 있습니다.
그래서 상세하게 적는 것보다는 간략하게 적는 것이 좋습니다.🙂

2021-10-28 09:01 UTC, gshduet commented on students/sanghyun/users/views.py
> +                return JsonResponse({"MESSAGE": "CHECK_YOUR_EMAIL/PASSWORD"}, status = 400)
사실 에러 메시지 작성하면서도 너무 친절한게 아닌가 싶어서 긴가민가 했습니다..ㅎㅎ 감사합니다!

2021-10-29 03:13 UTC, ghost approved these changes
LGTM 🥳

2021-10-29 03:14 UTC, merged